<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Oxymel' => $vendorDir . '/automattic/wxr-generator/lib/class-oxymel.php',
    'OxymelException' => $vendorDir . '/automattic/wxr-generator/lib/class-oxymel.php',
    'SubstackImporter\\Converter' => $baseDir . '/includes/class-converter.php',
    'SubstackImporter\\Importer_Admin' => $baseDir . '/includes/class-importer-admin.php',
    'WXR_Generator\\Buffer_Writer' => $vendorDir . '/automattic/wxr-generator/lib/class-buffer-writer.php',
    'WXR_Generator\\File_Writer' => $vendorDir . '/automattic/wxr-generator/lib/class-file-writer.php',
    'WXR_Generator\\Generator' => $vendorDir . '/automattic/wxr-generator/lib/class-generator.php',
    'WXR_Generator\\Writer_Interface' => $vendorDir . '/automattic/wxr-generator/lib/class-writer-interface.php',
);
